---
# tasks file for ansible-role-git-repository

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ git-repository_log_dir }}"
    mode: 0755
    owner: "{{ git-repository_user }}"
    group: "{{ git-repository_group }}"
    state: directory
  notify: Restart git-repository

- name: Create db directory
  file:
    path: "{{ git-repository_db_dir }}"
    mode: 0755
    owner: "{{ git-repository_user }}"
    group: "{{ git-repository_group }}"
    state: directory
  notify: Restart git-repository

- name: Create git-repository.conf
  template:
    src: git-repository.conf.j2
    dest: "{{ git-repository_conf_file }}"
    validate: echo %s
  notify: Restart git-repository

- name: Start git-repository
  service:
    name: "{{ git-repository_service }}"
    enabled: true
    state: started
